In [ ]:
import pandas as pd
data = pd.read_csv('/content/books.csv')
data

,Unnamed: 0,Title,Author,Description,Pages,Publication year,Publisher,Cover,Category,Subcategory,Price
0,0,فى فقه الصراع على القدس وفلسطين,محمد عمارة,الإسلامية كانت القدس رمز الصراع وبوابة الانتص...,180.0,2006.0,دار الشروق – مصر,غلاف ورقي,الأدب والخيال,الأدب الإسلامي,15.00
1,1,الرد على شبهات المستشرقين في السيرة النبوية(3),محمد بن عبد الرزاق اسود,None,86.0,2017.0,دار طيبة للنشر والتوزيع,غلاف ورقي,الأدب والخيال,الأدب الإسلامي,15.00
2,2,القصص التربوية عند الشيخ محمد تقي فلسفي,لطيف الراشدي,None,420.0,0.0,دار الكاتب العربي للطباعة والنشر,غلاف كرتوني,الأدب والخيال,الأدب الإسلامي,37.50
3,3,باب السلام,الأستاذ الدكتور عبدالوهاب إبراهيم أبو سليمان,None,494.0,2013.0,تارة الدولية,غلاف ورقي,الأدب والخيال,الأدب الإسلامي,100.02
4,4,تسبيح الروح,طراد حمادة,None,144.0,0.0,دار العلم للطباعة والنشر والتوزيع,غلاف عادي,الأدب والخيال,الأدب الإسلامي,18.75
...,...,...,...,...,...,...,...,...,...,...,...
7011,9026,ولاء حتى الفناء,الأمير شكيب أرسلان,None,254.0,0.0,المركز اللبناني للدراسات,غلاف عادي,الصحافة والإعلام,عام,39.75
7012,9027,The Beirut Review No.7,مجموعة مؤلفين,None,282.0,2011.0,المؤسسة العربية للدراسات والنشر,غلاف ورقي,الصحافة والإعلام,عام,45.00
7013,9028,نافذة على الإعلام العربي والدولي,علاء هادي,يعرض الكتاب معلومات مهمّة عن وسائل الإعلام ال...,368.0,2012.0,دار الآداب,غلاف ورقي,الصحافة والإعلام,عام,56.25
7014,9029,إمرأةٌ تحدق في الشمس,نوال السعداوي,تواكب نوال السعداوي في هذا الكتاب ثورة الشباب...,280.0,2005.0,مكتبة العبيكان,غلاف ورقي,الصحافة والإعلام,عام,30.00
7015,9030,كيف تكونين ناجحة ومحبوبة؟,عدنان الطرشة,يتضمن هذا الكتاب أسباب النجاح الرئيسة لأكثر ا...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import numpy as np

In [ ]:
# prompt: code for know exist of none

import pandas as pd

# Assuming 'data' DataFrame is already loaded as in the previous example
# data = pd.read_csv('/content/books.csv')

# Check for the existence of any NaN values in the entire DataFrame
if data.isnull().values.any():
    print("The DataFrame contains None values.")
else:
    print("The DataFrame does not contain None values.")

# Check for NaN values in specific columns
for column in data.columns:
  if data[column].isnull().values.any():
    print(f"Column '{column}' contains None values")
  else:
    print(f"Column '{column}' does not contain None values")

Unnamed: 0          0
Title               0
Author              0
Description         0
Pages               1
Publication year    1
Publisher           1
Cover               1
Category            1
Subcategory         1
Price               1
dtype: int64

In [ ]:
data.to_csv('books.csv',index=False,encoding='utf-8')

In [ ]:
data.isnull().values.any()

np.True_

In [ ]:
data.fillna('NaN')

,Unnamed: 0,Title,Author,Description,Pages,Publication year,Publisher,Cover,Category,Subcategory,Price
0,0,فى فقه الصراع على القدس وفلسطين,محمد عمارة,الإسلامية كانت القدس رمز الصراع وبوابة الانتص...,180.0,2006.0,دار الشروق – مصر,غلاف ورقي,الأدب والخيال,الأدب الإسلامي,15.0
1,1,الرد على شبهات المستشرقين في السيرة النبوية(3),محمد بن عبد الرزاق اسود,None,86.0,2017.0,دار طيبة للنشر والتوزيع,غلاف ورقي,الأدب والخيال,الأدب الإسلامي,15.0
2,2,القصص التربوية عند الشيخ محمد تقي فلسفي,لطيف الراشدي,None,420.0,0.0,دار الكاتب العربي للطباعة والنشر,غلاف كرتوني,الأدب والخيال,الأدب الإسلامي,37.5
3,3,باب السلام,الأستاذ الدكتور عبدالوهاب إبراهيم أبو سليمان,None,494.0,2013.0,تارة الدولية,غلاف ورقي,الأدب والخيال,الأدب الإسلامي,100.02
4,4,تسبيح الروح,طراد حمادة,None,144.0,0.0,دار العلم للطباعة والنشر والتوزيع,غلاف عادي,الأدب والخيال,الأدب الإسلامي,18.75
...,...,...,...,...,...,...,...,...,...,...,...
7011,9026,ولاء حتى الفناء,الأمير شكيب أرسلان,None,254.0,0.0,المركز اللبناني للدراسات,غلاف عادي,الصحافة والإعلام,عام,39.75
7012,9027,The Beirut Review No.7,مجموعة مؤلفين,None,282.0,2011.0,المؤسسة العربية للدراسات والنشر,غلاف ورقي,الصحافة والإعلام,عام,45.0
7013,9028,نافذة على الإعلام العربي والدولي,علاء هادي,يعرض الكتاب معلومات مهمّة عن وسائل الإعلام ال...,368.0,2012.0,دار الآداب,غلاف ورقي,الصحافة والإعلام,عام,56.25
7014,9029,إمرأةٌ تحدق في الشمس,نوال السعداوي,تواكب نوال السعداوي في هذا الكتاب ثورة الشباب...,280.0,2005.0,مكتبة العبيكان,غلاف ورقي,الصحافة والإعلام,عام,30.0
7015,9030,كيف تكونين ناجحة ومحبوبة؟,عدنان الطرشة,يتضمن هذا الكتاب أسباب النجاح الرئيسة لأكثر ا...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.isna().sum()

Unnamed: 0          0
Title               0
Author              0
Description         0
Pages               1
Publication year    1
Publisher           1
Cover               1
Category            1
Subcategory         1
Price               1
dtype: int64

In [ ]:
data['Description'].str.contains('None', case=False).sum()

np.int64(3594)

In [ ]:
data.drop(columns=['Description'],inplace=True)

In [ ]:
data.to_csv('books.csv',index=False,encoding='utf-8')

In [ ]:
data

,Unnamed: 0,Title,Author,Pages,Publication year,Publisher,Cover,Category,Subcategory,Price
0,0,فى فقه الصراع على القدس وفلسطين,محمد عمارة,180.0,2006.0,دار الشروق – مصر,غلاف ورقي,الأدب والخيال,الأدب الإسلامي,15.00
1,1,الرد على شبهات المستشرقين في السيرة النبوية(3),محمد بن عبد الرزاق اسود,86.0,2017.0,دار طيبة للنشر والتوزيع,غلاف ورقي,الأدب والخيال,الأدب الإسلامي,15.00
2,2,القصص التربوية عند الشيخ محمد تقي فلسفي,لطيف الراشدي,420.0,0.0,دار الكاتب العربي للطباعة والنشر,غلاف كرتوني,الأدب والخيال,الأدب الإسلامي,37.50
3,3,باب السلام,الأستاذ الدكتور عبدالوهاب إبراهيم أبو سليمان,494.0,2013.0,تارة الدولية,غلاف ورقي,الأدب والخيال,الأدب الإسلامي,100.02
4,4,تسبيح الروح,طراد حمادة,144.0,0.0,دار العلم للطباعة والنشر والتوزيع,غلاف عادي,الأدب والخيال,الأدب الإسلامي,18.75
...,...,...,...,...,...,...,...,...,...,...
7011,9026,ولاء حتى الفناء,الأمير شكيب أرسلان,254.0,0.0,المركز اللبناني للدراسات,غلاف عادي,الصحافة والإعلام,عام,39.75
7012,9027,The Beirut Review No.7,مجموعة مؤلفين,282.0,2011.0,المؤسسة العربية للدراسات والنشر,غلاف ورقي,الصحافة والإعلام,عام,45.00
7013,9028,نافذة على الإعلام العربي والدولي,علاء هادي,368.0,2012.0,دار الآداب,غلاف ورقي,الصحافة والإعلام,عام,56.25
7014,9029,إمرأةٌ تحدق في الشمس,نوال السعداوي,280.0,2005.0,مكتبة العبيكان,غلاف ورقي,الصحافة والإعلام,عام,30.00
7015,9030,كيف تكونين ناجحة ومحبوبة؟,عدنان الطرشة,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
(data['Publication year'] == 0).sum()

np.int64(2234)

In [ ]:
data.loc[data['Publication year'] == 0.0, 'Publication year'] = np.nan

In [ ]:
data['Publication year']

0       2006.0
1       2017.0
2          NaN
3       2013.0
4          NaN
         ...
7011       NaN
7012    2011.0
7013    2012.0
7014    2005.0
7015       NaN
Name: Publication year, Length: 7016, dtype: float64

In [ ]:
data.to_csv('books.csv',index=False,encoding='utf-8')

In [ ]:
(data['Publication year'] == 0.0).sum()

np.int64(0)

In [ ]:
data['Pages']

0       180.0
1        86.0
2       420.0
3       494.0
4       144.0
        ...
7011    254.0
7012    282.0
7013    368.0
7014    280.0
7015      NaN
Name: Pages, Length: 7016, dtype: float64